config/routes.rb
Rails.application.routes.draw do
  get 'challenges/new'

  get 'challenges/view'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @ignore_container = true
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_carousel.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
	</ol>

	<div class="carousel-inner">
		<div class="item active item1">
			<div class="container">
				<div class="carousel-caption">
					<h1>myFit just for your for free</h1>
					<p>
						Create and share your fitness plan.
					</p>
					<p>
						<%= link_to "Sign up now!", signup_path,
						class: "btn btn-lg btn-success" %>
					</p>
				</div>
			</div>
		</div>
		<div class="item item2">
			<div class="container">
				<div class="carousel-caption">
					<h1>myFit just for your for free</h1>
					<p>
						Create and share your fitness plan.
					</p>
					<p>
						<%= link_to "Sign up now!", signup_path,
						class: "btn btn-lg btn-success" %>
					</p>
				</div>
			</div>
		</div>
		<div class="item item3">
			<div class="container">
				<div class="carousel-caption">
					<h1>myFit just for your for free</h1>
					<p>
						Create and share your fitness plan.
					</p>
					<p>
						<%= link_to "Sign up now!", signup_path,
						class: "btn btn-lg btn-success" %>
					</p>
				</div>
			</div>
		</div>
	</div>
	<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->

app/views/static_pages/_logged_home.html.erb
<div class="row">
  <aside class="col-xs-12 col-sm-4 col-md-4 left-menu">
    <section class="user_info">
        <%= render 'shared/user_info' %>
    </section>

    <hr>
 <section class="stats">
        <%= render 'shared/trainings_info' %>
    </section>
        <hr>
    <section class="stats">
        <%= render 'shared/stats' %>
    </section>
    <hr>
     <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
  </aside>
  <div class="col-xs-12 col-sm-8 col-md-8">
    <div class="row up-margin">
        <div class="col-xs-6 col-sm-6 col-md-4 down-margin-small">
         <%= image_tag "logged_home/plan.jpg", :alt => "Personar trainer", :class => "featurette-image img-responsive img-rounded down-margin-small", :style => "width: 100%;" %>
 

            <button type="button" class="btn btn-success btn-lg btn-block">Workouts</button>
        </div>

           <div class="col-xs-6 col-sm-6 col-md-4 down-margin-small">
          <%= image_tag "logged_home/challenge.jpg", :alt => "Personar trainer", :class => "featurette-image img-responsive img-rounded down-margin-small", :style => "width: 100%;" %>

          <%= link_to "New challenge", challenges_new_path,
            class: "btn btn-warning btn-lg btn-block" %>
        </div>

           <div class="col-xs-6 col-sm-6 col-md-4 down-margin-small">
          <%= image_tag "logged_home/achievement.jpg", :alt => "Personar trainer", :class => "featurette-image img-responsive img-rounded down-margin-small", :style => "width: 100%;" %>
          <button type="button" class="btn btn-danger btn-lg btn-block">Achievements</button>
        </div>
    </div>       
    <h3>News</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/_not_logged_home.html.erb
<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

	<!-- Three columns of text below the carousel -->
	<div class="row">
		<div class="col-lg-4">
			<%= image_tag "home/kettle.jpg", :class => "img-circle", :style => "width: 140px; height: 140px;" %>
			<h1>Continous</h1>
			<p>
				Make each your each training unique opportunity for breaking your bundaries. Learn online about your progress and adjust your needs.
			</p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4">
			<%= image_tag "home/kettle.jpg", :class => "img-circle", :style => "width: 140px; height: 140px;" %>
			<h1>Training</h1>
			<p>
				Create and share your own unique training plan for free. No more papers on the gym, no more forgetting what to do next.
			</p>
		</div><!-- /.col-lg-4 -->
		<div class="col-lg-4">
			<%= image_tag "home/kettle.jpg", :class => "img-circle", :style => "width: 140px; height: 140px;" %>
			<h1>Improvemet</h1>
			<p>
				Be online and check your progress comparing to previous trainings or expectations.
			</p>

		</div><!-- /.col-lg-4 -->
	</div><!-- /.row -->

	<!-- START THE FEATURETTES -->

	<hr class="featurette-divider">
	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading">Have your personal trainer always online. <span class="text-muted">Challenge yourself and keep your progress constant.</span></h2>
			<p class="lead">
				Take your training into your hand and monitor your progress live on the gym. Time to change your oridnary plan for something really awesome.
			</p>
		</div>
		<div class="col-md-5">
			<%= image_tag "home/personal_trainer.jpg", :alt => "Personar trainer", :class => "featurette-image img-responsive img-rounded", :style => "width: 100%;" %>
		</div>
	</div>

	<hr class="featurette-divider">
	<div class="row featurette">
		<div class="col-md-5">
			<%= image_tag "home/friends.jpg", :alt => "Personar trainer", :class => "featurette-image img-responsive img-rounded", :style => "width: 100%;" %>
		</div>
		<div class="col-md-7">
			<h2 class="featurette-heading">Share your plan with your fiends. <span class="text-muted">Make it social.</span></h2>
			<p class="lead">
				Hight time to share your plan with other. Do you also want to share your results ? Why not ! Move your daily workaout into next dimension.
			</p>
		</div>
	</div>

	<hr class="featurette-divider">
	<div class="row featurette">
		<div class="col-md-7">
			<h2 class="featurette-heading">No more excuses. <span class="text-muted">Monitor your progress online and decide about the next steps.</span></h2>
			<p class="lead">
				Take your training into your hand and monitor your progress live on the gym. Time to change your oridnary plan for something really awesome.
			</p>
		</div>
		<div class="col-md-5">
			<%= image_tag "home/third.jpg", :alt => "Personar trainer", :class => "featurette-image img-responsive img-rounded", :style => "width: 100%;" %>
		</div>
	</div>
	
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <% provide(:title, 'Welcome ' + current_user.name) %>
  <%= render 'static_pages/logged_home' %>
<% else %>
  <% provide(:title, 'Welcome') %>
  <%= render 'static_pages/not_logged_home' %>
<% end %>