config/routes.rb
Rails.application.routes.draw do
  get 'challenges/new'

  get 'challenges/view'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.trainMood.com/">TrainMood</a>
    by <a href="http://www.michaelhartl.com/">Norbert Kosmal</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms of use",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TrainMood", root_path, id: "logo", class: "navbar-brand"%>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right gold-links">
        <% if logged_in? %>
        <%= render 'layouts/logged_header_menu' %>
        <% else %>
        <%= render 'layouts/not_logged_header_menu' %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_logged_header_menu.html.erb
<li>
	<%= link_to "Users", users_path %>
</li>
<li class="dropdown">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <span class="caret"></span></a>
	<ul class="dropdown-menu" role="menu">

		<li>
			<%= link_to "Profile", current_user %>
		</li>
		<li>
			<%= link_to "Settings", edit_user_path(current_user) %>
		</li>
		<li class="divider"></li>
		<li>
			<%= link_to "Log out", logout_path, method: "delete" %>
		</li>
	</ul>
</li>

app/views/layouts/_not_logged_header_menu.html.erb
<li>
	<%= link_to "Log in", login_path %>
</li>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <% if @ignore_container != nil %>
      <div class="container-fluid no-padding">
        <%= render 'static_pages/carousel' %>
      </div>
    <% end %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>